### ISSUE TITLE
Organisation and User Details

### ISSUE THREAD

**Issue by MihlaliMgwebi** [COS301-SE-2021/EduGo#25]
@sthenyandeni @simekani18
question

Backend Boys! In the OrganisationModels file, I want to confirm whether or not the User details should be parameter variables for the Organisation Model's constructor or whether I must make use of the User class' variables somehow instead? Looking at the request body on Postman, I'm leaning on the first option. Please also inform me on if all these parameters are necessary to create an org or if they have default values.

**Comment by simekani18** [comment]
Utilize the request body that is on postman
