### ISSUE TITLE
Fatal bug when registering new user

### ISSUE THREAD

**Issue by sthenyandeni** [COS301-SE-2021/EduGo#27]
After creating an unverified user, when trying to register them, they are successfully registered but do not appear to belong to the organisation (the organisationId field is null)
![Screenshot 2021-08-03 at 14 02 50](https://user-images.githubusercontent.com/53145212/128012086-9468233e-8d71-455d-b760-52a16ad6c103.png)

**Comment by simekani18** [comment]
Worked on it should be fine now
