### ISSUE TITLE
Create subject bug

### ISSUE THREAD

**Issue by sthenyandeni** [COS301-SE-2021/EduGo#29]
When creating duplicate subjects, the response is a code 500 with the actual db error being sent instead of a custom error and a code 4XX response

**Comment by sthenyandeni** [comment]
<img width="1240" alt="Screenshot 2021-08-03 at 23 12 22" src="https://user-images.githubusercontent.com/53145212/128086834-16b5cfff-45b0-4f97-90f1-2c03fe826f85.png">

**Comment by simekani18** [comment]
Issue is fixed now
